/********************************************************************
 This file was generated by menu Tool of Rockchip Co., Ltd.

 Generate time: 2016-6-8 14:10:44

 Tool Version: 3.0.0.0

 End.
********************************************************************/
#ifndef          _MENU_RESOURCE_H
#define          _MENU_RESOURCE_H


#define          MENU_ITEM_LENGTH            (unsigned short)250             // The length of menu item in bytes
#define          TOTAL_MENU_ITEM             (unsigned short)197
#define          TOTAL_LANAUAGE_NUM          (unsigned short)19
#define          MAX_SUBMENU_NUM             (unsigned short)17
#define          MENU_CONTENT_OFFSET         (unsigned short)50





#define          SID_MUSIC                                        (unsigned short)0x0000       //Music
#define          SID_DLNA                                         (unsigned short)0x0001       //DLNA
#define          SID_MAINMENU_BLUETOOTH                           (unsigned short)0x0002       //Bluetooth
#define          SID_LINE_IN                                      (unsigned short)0x0003       //Line in
#define          SID_XXX                                          (unsigned short)0x0004       //XXX
#define          SID_5_1_CHANNEL                                  (unsigned short)0x0005       //5.1 Channel
#define          SID_RADIO                                        (unsigned short)0x0006       //Radio
#define          SID_RECORD                                       (unsigned short)0x0007       //Record
#define          SID_TEXT                                         (unsigned short)0x0008       //Text
#define          SID_EXPLORER                                     (unsigned short)0x0009       //Explorer
#define          SID_MAIN_SETTINGS                                (unsigned short)0x000a       //Settings
#define          SID_VIDEO                                        (unsigned short)0x000b       //Video
#define          SID_PHOTO                                        (unsigned short)0x000c       //Photo
#define          SID_FM_RADIO                                     (unsigned short)0x000d       //FM Radio 
#define          SID_GAME                                         (unsigned short)0x000e       //Game
#define          SID_NOR                                          (unsigned short)0x000f       //NOR
#define          SID_PLAYFX                                       (unsigned short)0x0010       //PlayFX
#define          SID_ROCK                                         (unsigned short)0x0011       //ROCK
#define          SID_POP                                          (unsigned short)0x0012       //POP
#define          SID_CLASS                                        (unsigned short)0x0013       //CLASS
#define          SID_BASS                                         (unsigned short)0x0014       //BASS
#define          SID_JAZZ                                         (unsigned short)0x0015       //JAZZ
#define          SID_USER                                         (unsigned short)0x0016       //USER
#define          SID_UNKNOWN                                      (unsigned short)0x0017       //~Unknown~
#define          SID_NO_LYRIC_FILE                                (unsigned short)0x0018       //~No Lyric File~
#define          SID_NO_PRESET                                    (unsigned short)0x0019       //No Preset
#define          SID_MANUAL_MOD                                   (unsigned short)0x001a       //Manual Mode
#define          SID_PRESET_MOD                                   (unsigned short)0x001b       //Preset Mode
#define          SID_MEM                                          (unsigned short)0x001c       //Add Preset
#define          SID_DEL                                          (unsigned short)0x001d       //Delete Preset
#define          SID_AUTO_MOD                                     (unsigned short)0x001e       //Auto Preset Mode
#define          SID_WITHOUT_THE_CHANNEL                          (unsigned short)0x001f       //Without The Channel
#define          SID_WITHOUT_CHANNEL                              (unsigned short)0x0020       //Without Channel
#define          SID_RECORD                                       (unsigned short)0x0021       //Record
#define          SID_PLAY_REC_DATA                                (unsigned short)0x0022       //Play Rec List
#define          SID_DELETE_REC_DATA                              (unsigned short)0x0023       //Delete Rec Data
#define          SID_DELETE_ALL                                   (unsigned short)0x0024       //Delete All Channel
#define          SID_ALL_REC_DATA                                 (unsigned short)0x0025       //All Rec Data
#define          SID_DELETE_ALL_COMFIRM                           (unsigned short)0x0026       //Delete All
#define          SID_DELETING                                     (unsigned short)0x0027       //Deleting…
#define          SID_SAVE_CHANNEL                                 (unsigned short)0x0028       //Save Channel
#define          SID_DELETE_CHANNEL                               (unsigned short)0x0029       //Delete Channel
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x002a       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x002b       //Load BookMark
#define          SID_MIC_REC                                      (unsigned short)0x002c       //MIC REC
#define          SID_LINE_IN_REC                                  (unsigned short)0x002d       //LINE IN REC
#define          SID_FM_REC                                       (unsigned short)0x002e       //FM REC
#define          SID_RECORDING                                    (unsigned short)0x002f       //Recording...
#define          SID_RECORD_PAUSE                                 (unsigned short)0x0030       //Pause...
#define          SID_RECORD_PREPARE                               (unsigned short)0x0031       //Prepare...
#define          SID_RECORD_SAVE_FILE                             (unsigned short)0x0032       //Save File...
#define          SID_CREAT_FILE_ERROR                             (unsigned short)0x0033       //Creat File Error!
#define          SID_DISK_IS_FULL                                 (unsigned short)0x0034       //Disk Is Full!
#define          SID_FLASH_MEMERY                                 (unsigned short)0x0035       //Flash Memery
#define          SID_MINISD_CARD                                  (unsigned short)0x0036       //MiniSD Card 
#define          SID_COULD_NOT_CONTINUE                           (unsigned short)0x0037       //Could not continue
#define          SID_WARNING                                      (unsigned short)0x0038       //Warning
#define          SID_YES                                          (unsigned short)0x0039       //Yes
#define          SID_NO                                           (unsigned short)0x003a       //No
#define          SID_EXIT                                         (unsigned short)0x003b       //Exit
#define          SID_PLEASE_WAIT                                  (unsigned short)0x003c       //Please Wait……
#define          SID_LOW_BATTERY                                  (unsigned short)0x003d       //Low Battery!
#define          SID_FIRMWARE_UPGRADE                             (unsigned short)0x003e       //Firmware Upgrade?
#define          SID_PLEASE_INSERT_USB                            (unsigned short)0x003f       //Connect USB…… 
#define          SID_RESTORE_DEFAULT_VAL                          (unsigned short)0x0040       //Restorable?
#define          SID_FORMAT_DISK                                  (unsigned short)0x0041       //Format Disk?
#define          SID_FORMATTING                                   (unsigned short)0x0042       //Formatting……
#define          SID_FILE_FORMAT_ERROR                            (unsigned short)0x0043       //File Format Error!
#define          SID_NO_MUSIC_FILE                                (unsigned short)0x0044       //No Music File!
#define          SID_DELETE_FILE                                  (unsigned short)0x0045       //Delete File
#define          SID_DELETE_FILE_ASK                              (unsigned short)0x0046       //Delete File?
#define          SID_DELETING_FILE                                (unsigned short)0x0047       //Deleting File…… 
#define          SID_MUSIC_FILE                                   (unsigned short)0x0048       //Music File
#define          SID_VIDEO_FILE                                   (unsigned short)0x0049       //Video File
#define          SID_TEXT_FILE                                    (unsigned short)0x004a       //Text
#define          SID_PICTURE_FILE                                 (unsigned short)0x004b       //Picture File
#define          SID_EXPLORER                                     (unsigned short)0x004c       //Explorer
#define          SID_C_FLASH                                      (unsigned short)0x004d       //C:FLASH
#define          SID_D_FLASH                                      (unsigned short)0x004e       //D:FLASH
#define          SID_D_SD_CARD                                    (unsigned short)0x004f       //D:SD CARD
#define          SID_E_SD_CARD                                    (unsigned short)0x0050       //E:SD CARD
#define          SID_NO_FILE                                      (unsigned short)0x0051       //No File!
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x0052       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x0053       //Load BookMark
#define          SID_WRITE_FILE_ERROR                             (unsigned short)0x0054       //Write File Error!
#define          SID_CLOSE_FILE_ERROR                             (unsigned short)0x0055       //Close File Error!
#define          SID_MEDIALIB                                     (unsigned short)0x0056       //medialib
#define          SID_PLAYING                                      (unsigned short)0x0057       //Go to playback screen.
#define          SID_ALL_MUISC_FILE                               (unsigned short)0x0058       //All Songs
#define          SID_ARTIST                                       (unsigned short)0x0059       //Artists
#define          SID_ALBUM                                        (unsigned short)0x005a       //Albums
#define          SID_GENRE                                        (unsigned short)0x005b       //Genres
#define          SID_PLAY_LIST                                    (unsigned short)0x005c       //Playlist
#define          SID_DIR_LIST                                     (unsigned short)0x005d       //Folder
#define          SID_RECORE_FILE                                  (unsigned short)0x005e       //RECORE FILE
#define          SID_MY_FAVORITE                                  (unsigned short)0x005f       //My Favorite
#define          SID_UPDATE_MEDIALIB                              (unsigned short)0x0060       //MediaLib Update
#define          SID_UPDATEING_FIRMWARE                           (unsigned short)0x0061       //Firmware Upgrading…… 
#define          SID_RECOVER_FIRMWARE                             (unsigned short)0x0062       //Firmware Recoverying…… 
#define          SID_HOLDON_PLAY                                  (unsigned short)0x0063       //Breakpoint player
#define          SID_TITLE                                        (unsigned short)0x0064       //Title
#define          SID_ADD_FAVORITE                                 (unsigned short)0x0065       //Add To Favorite
#define          SID_CLEAR_FAVORITE                               (unsigned short)0x0066       //Clear Up
#define          SID_UPDATEING_MEDIALIB                           (unsigned short)0x0067       //MediaLib Update…… 
#define          SID_CONNECTING_USB                               (unsigned short)0x0068       //Connecting USB
#define          SID_CHARGING                                     (unsigned short)0x0069       //Charging
#define          SID_FULL_CHANGED                                 (unsigned short)0x006a       //Fully charged
#define          SID_CANNOT_CHARGE                                (unsigned short)0x006b       //Cannot charge
#define          SID_DATA_EX_NOT_DISCONNECT_LINE1                 (unsigned short)0x006c       //Do not
#define          SID_DATA_EX_NOT_DISCONNECT_LINE2                 (unsigned short)0x006d       //disconnect
#define          SID_DATA_EX_NOT_DISCONNECT_LINE3                 (unsigned short)0x006e       //disconnect
#define          SID_VOLUME                                       (unsigned short)0x006f       //Volume
#define          SID_UPDATING_LIBRARY                             (unsigned short)0x0070       //Updating Library
#define          SID_WIFI_TURN_ON                                 (unsigned short)0x0071       //Please turn on WIFI.
#define          SID_WIFI_TURN_OFF                                (unsigned short)0x0072       //Please turn off WIFI.
#define          SID_WIFI_TURNNING_ON                             (unsigned short)0x0073       //Turnning on WIFI……
#define          SID_WIFI_TURNNING_OFF                            (unsigned short)0x0074       //Turnning off WIFI……
#define          SID_WIFI_TURNON_FAILED                           (unsigned short)0x0075       //Turn on WIFI Failed!
#define          SID_WIFI_CONNECT_FAILED                          (unsigned short)0x0076       //Connect WIFI Failed!
#define          SID_BT_TURN_ON                                   (unsigned short)0x0077       //Please turn on Bluetooth.
#define          SID_BT_TURN_OFF                                  (unsigned short)0x0078       //Please turn off Bluetooth.
#define          SID_BT_TURNNING_ON                               (unsigned short)0x0079       //Turnning on bluetooth……
#define          SID_BT_TURNNING_OFF                              (unsigned short)0x007a       //Turnning off bluetooth……
#define          SID_BT_TURNON_FAILED                             (unsigned short)0x007b       //Turn on bluetooth Failed!
#define          SID_PLAYER_FAILED                                (unsigned short)0x007c       //Turn on player failed！
#define          SID_RECODING_STEREO                              (unsigned short)0x007d       //Stereo
#define          SID_RECODING_MONO                                (unsigned short)0x007e       //Mono
#define          SID_RECODING_BIT24                               (unsigned short)0x007f       //24bit
#define          SID_RECODING_BIT16                               (unsigned short)0x0080       //16bit
#define          SID_READY_SD_CARD                                (unsigned short)0x0081       //Ready to SD card......
//-----------------------------------------------------------------------------------------------------------------------------
//-------This is a menu-------
#define          SID_SETTINGS                                     (unsigned short)0x0082       //Settings
#define          SID_WLAN                                         (unsigned short)0x0083       //WLAN
#define          SID_WIFICONFIG                                   (unsigned short)0x0084       //WiFi Power
#define          SID_WIFICONFIG_ON_STA                            (unsigned short)0x0085       //On STA                [Function Index: 0000]
#define          SID_WIFICONFIG_ON_AP                             (unsigned short)0x0086       //On AP                 [Function Index: 0001]
#define          SID_WIFICONFIG_OFF                               (unsigned short)0x0087       //Off                   [Function Index: 0002]
#define          SID_APCONFIG                                     (unsigned short)0x0088       //AP Config             [Function Index: 0003]
#define          SID_BLUETOOTH                                    (unsigned short)0x0089       //Bluetooth
#define          SID_BLUETOOTH_ON                                 (unsigned short)0x008a       //On                    [Function Index: 0004]
#define          SID_BLUETOOTH_OFF                                (unsigned short)0x008b       //Off                   [Function Index: 0005]
#define          SID_SETTING_MUSIC                                (unsigned short)0x008c       //Music Settings
#define          SID_MUSIC_SHUFFLE                                (unsigned short)0x008d       //Shuffle
#define          SID_MUSIC_SHUFFLE_OFF                            (unsigned short)0x008e       //Shuffle Off           [Function Index: 0006]
#define          SID_MUSIC_SHUFFLE_ON                             (unsigned short)0x008f       //Shuffle On            [Function Index: 0007]
#define          SID_MUSIC_REPEAT_MODE                            (unsigned short)0x0090       //Repeat
#define          SID_MUSIC_FOLDER_ONCE                            (unsigned short)0x0091       //Off                   [Function Index: 0008]
#define          SID_MUSIC_FOLDER_REPEAT                          (unsigned short)0x0092       //Repeat                [Function Index: 0009]
#define          SID_MUSIC_REPEAT_ONE                             (unsigned short)0x0093       //Repeat 1 Song         [Function Index: 0010]
#define          SID_EQ_SELECT                                    (unsigned short)0x0094       //Equalizer
#define          SID_EQ_NONE                                      (unsigned short)0x0095       //Normal                [Function Index: 0011]
#define          SID_EQ_BASS                                      (unsigned short)0x0096       //Bass                  [Function Index: 0012]
#define          SID_EQ_HEAVY                                     (unsigned short)0x0097       //Heavy                 [Function Index: 0013]
#define          SID_EQ_POP                                       (unsigned short)0x0098       //Pop                   [Function Index: 0014]
#define          SID_EQ_JAZZ                                      (unsigned short)0x0099       //Jazz                  [Function Index: 0015]
#define          SID_EQ_UNIQUE                                    (unsigned short)0x009a       //Unique                [Function Index: 0016]
#define          SID_EQ_CUSTOM                                    (unsigned short)0x009b       //Custom                [Function Index: 0017]
#define          SID_SETTING_RADIO                                (unsigned short)0x009c       //FM Settings
#define          SID_RADIO_SCAN_SENSITIVITY                       (unsigned short)0x009d       //Scan Sensitivity
#define          SID_SCAN_SENSITIVITY_HIGH                        (unsigned short)0x009e       //High                  [Function Index: 0018]
#define          SID_SCAN_SENSITIVITY_LOW                         (unsigned short)0x009f       //Low                   [Function Index: 0019]
#define          SID_FM_AUTO_PRESET                               (unsigned short)0x00a0       //FM Auto Preset        [Function Index: 0020]
#define          SID_SETTING_COMMON                               (unsigned short)0x00a1       //Common Settings
#define          SID_COMMON_SCREEN_OFF_TIMER                      (unsigned short)0x00a2       //Screen Off Timer
#define          SID_SCREEN_OFF_15_SEC                            (unsigned short)0x00a3       //15 Seconds            [Function Index: 0021]
#define          SID_SCREEN_OFF_30_SEC                            (unsigned short)0x00a4       //30 Seconds            [Function Index: 0022]
#define          SID_SCREEN_OFF_1_MIN                             (unsigned short)0x00a5       //1 Minute              [Function Index: 0023]
#define          SID_SCREEN_OFF_3_MIN                             (unsigned short)0x00a6       //3 Minutes             [Function Index: 0024]
#define          SID_SCREEN_OFF_5_MIN                             (unsigned short)0x00a7       //5 Minutes             [Function Index: 0025]
#define          SID_SCREEN_OFF_30_MIN                            (unsigned short)0x00a8       //30 Minutes            [Function Index: 0026]
#define          SID_COMMON_BRIGHTNESS                            (unsigned short)0x00a9       //Brightness
#define          SID_LUM_1                                        (unsigned short)0x00aa       //1                     [Function Index: 0027]
#define          SID_LUM_2                                        (unsigned short)0x00ab       //2                     [Function Index: 0028]
#define          SID_LUM_3                                        (unsigned short)0x00ac       //3                     [Function Index: 0029]
#define          SID_LUM_4                                        (unsigned short)0x00ad       //4                     [Function Index: 0030]
#define          SID_LUM_5                                        (unsigned short)0x00ae       //5                     [Function Index: 0031]
#define          SID_SYS_ABOUT                                    (unsigned short)0x00af       //Information           [Function Index: 0032]
#define          SID_LANGUAGE                                     (unsigned short)0x00b0       //Language
#define          SID_CHINESE_S                                    (unsigned short)0x00b1       //简体中文              [Function Index: 0033]
#define          SID_CHINESE_T                                    (unsigned short)0x00b2       //繁體中文              [Function Index: 0034]
#define          SID_ENGLISH                                      (unsigned short)0x00b3       //English               [Function Index: 0035]
#define          SID_KOREAN                                       (unsigned short)0x00b4       //??                    [Function Index: 0036]
#define          SID_JAPANESE                                     (unsigned short)0x00b5       //日本語                [Function Index: 0037]
#define          SID_FRENCH                                       (unsigned short)0x00b6       //Fran?ais              [Function Index: 0038]
#define          SID_GERMAN                                       (unsigned short)0x00b7       //Deutsch               [Function Index: 0039]
#define          SID_PORTUGUESE                                   (unsigned short)0x00b8       //Português            [Function Index: 0040]
#define          SID_RUSSIAN                                      (unsigned short)0x00b9       //Русский        [Function Index: 0041]
#define          SID_SWEDISH                                      (unsigned short)0x00ba       //Svenska               [Function Index: 0042]
#define          SID_THAI                                         (unsigned short)0x00bb       //???????               [Function Index: 0043]
#define          SID_POLISH                                       (unsigned short)0x00bc       //j?zyk polski          [Function Index: 0044]
#define          SID_DENISH                                       (unsigned short)0x00bd       //Dansk                 [Function Index: 0045]
#define          SID_HOLLANDS                                     (unsigned short)0x00be       //Hollands              [Function Index: 0046]
#define          SID_GREEK                                        (unsigned short)0x00bf       //Ελληνικ?       [Function Index: 0047]
#define          SID_CZECHIC                                      (unsigned short)0x00c0       //?í?tina              [Function Index: 0048]
#define          SID_TURKISH                                      (unsigned short)0x00c1       //Türk?e               [Function Index: 0049]
#define          SID_SETTING_INITIALIZE                           (unsigned short)0x00c2       //Initialize
#define          SID_SYS_DEFAULT_SET                              (unsigned short)0x00c3       //Reset All Settings    [Function Index: 0050]
#define          SID_FORMAT_DISK                                  (unsigned short)0x00c4       //Format                [Function Index: 0051]





//-----------------------------------------------------------------------------------------------------------------------------
#define          SID_SETTINGS_ENTRY                               SID_SETTINGS       //Settings
#define          SID_SETTINGS_ENTRY_FUN_COUNTER                   0x0034


#endif
