/*
********************************************************************************************
*
*        Copyright (c):  Fuzhou Rockchip Electronics Co., Ltd
*                             All rights reserved.
*
* FileName: Bsp\EVK_V2.0\Scatter\ModuleInfoTab.h
* Owner: aaron.sun
* Date: 2015.6.10
* Time: 16:00:57
* Version: 1.0
* Desc:
* History:
*    <author>    <date>       <time>     <version>     <Desc>
*    aaron.sun     2015.6.10     16:00:57   1.0
********************************************************************************************
*/

#ifndef _MODULEINFO_H
#define _MODULEINFO_H

#undef  EXT
#ifdef _IN_MODULEINFO_
#define EXT
#else
#define EXT extern
#endif

/*
*-------------------------------------------------------------------------------
*
*                           Module Info
*
*-------------------------------------------------------------------------------
*/
//Segment ID Define
typedef enum
{
    //SysCode
    SEGMENT_ID_SYS,
    SEGMENT_ID_INIT,
    SEGMENT_ID_PMU,
    SEGMENT_ID_SUSPEND,
    SEGMENT_ID_RESUME,
    SEGMENT_ID_LININ_TASK,
    SEGMENT_ID_LININ_INIT,
    SEGMENT_ID_LININCONTROL_TASK,
    SEGMENT_ID_LININCONTROL_INIT,
    SEGMENT_ID_FMUI_TASK,
    SEGMENT_ID_FMUI_INIT,
    SEGMENT_ID_FMCONTROL_TASK,
    SEGMENT_ID_FMCONTROL_INIT,
    SEGMENT_ID_FM_DEV,
    SEGMENT_ID_FM_INIT,
    SEGMENT_ID_FM_SHELL,
    SEGMENT_ID_BROWSERUI_TASK,
    SEGMENT_ID_BROWSERUI_INIT,
    SEGMENT_ID_SYSTEMSETWIFISELECT_TASK,
    SEGMENT_ID_SYSTEMSETWIFISELECT_INIT,
    SEGMENT_ID_SYSTEMSET_TASK,
    SEGMENT_ID_SYSTEMSET_INIT,
    SEGMENT_ID_CHARGE_TASK,
    SEGMENT_ID_CHARGE_INIT,
    SEGMENT_ID_MUSIC_PLAY_MENU_TASK,
    SEGMENT_ID_MUSIC_PLAY_MENU_INIT,
    SEGMENT_ID_RECOD_TASK,
    SEGMENT_ID_RECOD_INIT,
    SEGMENT_ID_MEDIA_UPDATE,
    SEGMENT_ID_FILEINFO_SAVE,
    SEGMENT_ID_ID3,
    SEGMENT_ID_FILEINFO_SORT,
    SEGMENT_ID_MEDIA_LIBRARY_TASK_CODE,
    SEGMENT_ID_MEDIA_LIBRARY_TASK_INIT,
    SEGMENT_ID_MEDIA_BROWSER_TASK_CODE,
    SEGMENT_ID_MEDIA_BROWSER_TASK_INIT,
    SEGMENT_ID_USBSERVER_TASK,
    SEGMENT_ID_USBSERVER_INIT,
    SEGMENT_ID_MAIN_TASK,
    SEGMENT_ID_MAIN_MENU,
    SEGMENT_ID_MAIN_INIT,
    SEGMENT_ID_RECORD_SHELL,
    SEGMENT_ID_MUSIC_SHELL,
    SEGMENT_ID_EFFECT_MODULE,
    SEGMENT_ID_TIMER_DEV,
    SEGMENT_ID_TIMER_INIT,
    SEGMENT_ID_TIMER_SHELL,
    SEGMENT_ID_ADC_DEV,
    SEGMENT_ID_ADC_INIT,
    SEGMENT_ID_ADC_SHELL,
    SEGMENT_ID_KEY_DEV,
    SEGMENT_ID_KEY_INIT,
    SEGMENT_ID_KEY_SHELL,
    SEGMENT_ID_PWM_DEV,
    SEGMENT_ID_PWM_INIT,
    SEGMENT_ID_PWM_SHELL,
    SEGMENT_ID_VOP_DEV,
    SEGMENT_ID_VOP_INIT,
    SEGMENT_ID_VOP_SHELL,
    SEGMENT_ID_LCD_DEV,
    SEGMENT_ID_LCD_INIT,
    SEGMENT_ID_LCD_SHELL,
    SEGMENT_ID_DISPLAY_DEV,
    SEGMENT_ID_DISPLAY_INIT,
    SEGMENT_ID_DISPLAY_SHELL,
    SEGMENT_ID_GUI_TASK,
    SEGMENT_ID_GUI_INIT,
    SEGMENT_ID_GUI_SHELL,
    SEGMENT_ID_BCORE_DEV,
    SEGMENT_ID_BCORE_INIT,
    SEGMENT_ID_BCORE_SHELL,
    SEGMENT_ID_MSG_DEV,
    SEGMENT_ID_MSG_INIT,
    SEGMENT_ID_MSG_SHELL,
    SEGMENT_ID_DIR_DEV,
    SEGMENT_ID_DIR_INIT,
    SEGMENT_ID_DIR_SHELL,
    SEGMENT_ID_FILESTREAM_TASK,
    SEGMENT_ID_FILESTREAM_INIT,
    SEGMENT_ID_HTTP_TASK,
    SEGMENT_ID_HTTP_INIT,
    SEGMENT_ID_MEDIA_TASK,
    SEGMENT_ID_MEDIA_INIT,
    SEGMENT_ID_STREAMCONTROL_TASK,
    SEGMENT_ID_STREAMCONTROL_INIT,
    SEGMENT_ID_AUDIOCONTROL_TASK,
    SEGMENT_ID_AUDIOCONTROL_INIT,
    SEGMENT_ID_RECORDCONTROL_TASK,
    SEGMENT_ID_RECORDCONTROL_INIT,
    SEGMENT_ID_WAV_ENCODE,
    SEGMENT_ID_AMR_ENCODE,
    SEGMENT_ID_XXX_ENCODE,
    SEGMENT_ID_MP3_DECODE,
    SEGMENT_ID_XXX_DECODE,
    SEGMENT_ID_WAV_DECODE,
    SEGMENT_ID_AMR_DECODE,
    SEGMENT_ID_FLAC_DECODE,
    SEGMENT_ID_AAC_DECODE,
    SEGMENT_ID_APE_DECODE,
    SEGMENT_ID_OGG_DECODE,
    SEGMENT_ID_FLAC_HDECODE,
    SEGMENT_ID_ALAC_HDECODE,
    SEGMENT_ID_APE_HDECODE,
    SEGMENT_ID_SBC_DECODE,
    SEGMENT_ID_AEC,
    SEGMENT_ID_I2S_DEV,
    SEGMENT_ID_I2S_INIT,
    SEGMENT_ID_I2S_SHELL,
    SEGMENT_ID_ROCKCODEC_DEV,
    SEGMENT_ID_ROCKCODEC_INIT,
    SEGMENT_ID_ROCKCODEC_SHELL,
    SEGMENT_ID_AUDIO_DEV,
    SEGMENT_ID_AUDIO_INIT,
    SEGMENT_ID_AUDIO_SHELL,
    SEGMENT_ID_AUDIOSUB_TASK,
    SEGMENT_ID_AUDIOSUB_INIT,
    SEGMENT_ID_AUDIOMAIN_TASK,
    SEGMENT_ID_AUDIOMAIN_INIT,
    SEGMENT_ID_USBMSC_DEV,
    SEGMENT_ID_USBMSC_INIT,
    SEGMENT_ID_USBMSC_SHELL,
    SEGMENT_ID_MAILBOX_DEV,
    SEGMENT_ID_MAILBOX_INIT,
    SEGMENT_ID_MAILBOX_SHELL,
    SEGMENT_ID_RK618_DEV,
    SEGMENT_ID_RK618_INIT,
    SEGMENT_ID_RK618_SHELL,
    SEGMENT_ID_FIFO_DEV,
    SEGMENT_ID_FIFO_INIT,
    SEGMENT_ID_FIFO_SHELL,
    SEGMENT_ID_SD_DEV,
    SEGMENT_ID_SD_INIT,
    SEGMENT_ID_SD_SHELL,
    SEGMENT_ID_I2C_DEV,
    SEGMENT_ID_I2C_INIT,
    SEGMENT_ID_I2C_SHELL,
    SEGMENT_ID_USBOTG_DEV,
    SEGMENT_ID_USBOTG_INIT,
    SEGMENT_ID_USBOTG_SHELL,
    SEGMENT_ID_SDC_DEV,
    SEGMENT_ID_SDC_INIT,
    SEGMENT_ID_SDC_SHELL,
    SEGMENT_ID_DMA_SHELL,
    SEGMENT_ID_EMMC_DEV,
    SEGMENT_ID_EMMC_INIT,
    SEGMENT_ID_EMMC_SHELL,
    SEGMENT_ID_LUN_DEV,
    SEGMENT_ID_LUN_INIT,
    SEGMENT_ID_LUN_SHELL,
    SEGMENT_ID_PAR_DEV,
    SEGMENT_ID_PAR_INIT,
    SEGMENT_ID_PAR_SHELL,
    SEGMENT_ID_FAT_DEV,
    SEGMENT_ID_FAT_INIT,
    SEGMENT_ID_FAT_SHELL,
    SEGMENT_ID_FILE_DEV,
    SEGMENT_ID_FILE_INIT,
    SEGMENT_ID_FILE_SHELL,
    SEGMENT_ID_SDIO_DEV,
    SEGMENT_ID_SDIO_INIT,
    SEGMENT_ID_SDIO_SHELL,
    SEGMENT_ID_UART_DEV,
    SEGMENT_ID_UART_INIT,
    SEGMENT_ID_UART_SHELL,
    SEGMENT_ID_WDOG_DEV,
    SEGMENT_ID_WDOG_INIT,
    SEGMENT_ID_WDOG_SHELL,
    SEGMENT_ID_I6000_WIFI,
    SEGMENT_ID_I6000_WIFI2,
    SEGMENT_ID_I6000_WIFI_SHELL,
    SEGMENT_ID_WIFI_APPTASK_INIT,
    SEGMENT_ID_WIFI_APPTASK,
    SEGMENT_ID_AP6181_INIT,
    SEGMENT_ID_AP6181_WIFI,
    SEGMENT_ID_AP6181_SHELL,
    SEGMENT_ID_DLNA_INIT,
    SEGMENT_ID_DLNA_TASK_API,
    SEGMENT_ID_DLNA_SHELL,
    SEGMENT_ID_DLNA,
    SEGMENT_ID_UPNP,
    SEGMENT_ID_XML,
    SEGMENT_ID_XXX_INIT,
    SEGMENT_ID_XXX_SHELL,
    SEGMENT_ID_XXX,
    SEGMENT_ID_SWITCHPLAYER_SHELL,//JJJHHH 20161016
    SEGMENT_ID_CHANNELS_SPEAKER,
    SEGMENT_ID_SSL,
    SEGMENT_ID_LWIP,
    SEGMENT_ID_LWIP_API,
    SEGMENT_ID_PING_SHELL,
    SEGMENT_ID_IPCONFIG_SHELL,
    SEGMENT_ID_HTTP,
    SEGMENT_ID_HTTPD,
    SEGMENT_ID_MBEDTLS,
    SEGMENT_ID_BLUETOOTH,
    SEGMENT_ID_BLUETOOTH_SHELL,
    SEGMENT_ID_BLUETOOTH_LWBT,
    SEGMENT_ID_SPIFLASH_INIT,
    SEGMENT_ID_SPIFLASH_DEV,
    SEGMENT_ID_SPIFLASH_SHELL,
    SEGMENT_ID_SPI_DEV,
    SEGMENT_ID_SPI_INIT,
    SEGMENT_ID_SPI_SHELL,
    SEGMENT_ID_SPINOR_DEV,
    SEGMENT_ID_SPINOR_INIT,
    SEGMENT_ID_SPINOR_SHELL,
    SEGMENT_ID_WIFI_FIRMAVE_ONE,
    SEGMENT_ID_WIFI_FIRMAVE_TWO,
    SEGMENT_ID_WIFI_FIRMAVE_RKI6000,
    SEGMENT_ID_BT_FIRMAVE,
    SEGMENT_ID_AUDIO_EQ_DATA,
    SEGMENT_ID_DMR_DEVICE_DATA,
    SEGMENT_ID_DMR_CONNECTIONMANAGER_SERVICE_DATA,
    SEGMENT_ID_DMR_RENDERINGCONTROL_SERVICE_DATA,
    SEGMENT_ID_DMR_AVTRANSPORT_SERVICE_DATA,
    SEGMENT_ID_DMR_NAMINGBITMAP_DATA,
    SEGMENT_ID_DMR_NMSTRTPAGES_DATA,
    SEGMENT_ID_DMR_NAMEPAGES_DATA,
    SEGMENT_ID_SYS_CMD,
    SEGMENT_ID_DEV_CMD,
    SEGMENT_ID_TASK_CMD,
    SEGMENT_ID_CUSTOM_CMD,
    SEGMENT_ID_BB_CODE,
    SEGMENT_ID_MP3_DECODE_BIN,
    SEGMENT_ID_XXX_DECODE_BIN,
    SEGMENT_ID_WAV_DECODE_BIN,
    SEGMENT_ID_AMR_DECODE_BIN,
    SEGMENT_ID_FLAC_DECODE_BIN,
    SEGMENT_ID_AAC_DECODE_BIN,
    SEGMENT_ID_APE_DECODE_BIN,
    SEGMENT_ID_OGG_DECODE_BIN,
    SEGMENT_ID_FLAC_HDECODE_BIN,
    SEGMENT_ID_ALAC_HDECODE_BIN,
    SEGMENT_ID_APE_HDECODE_BIN,
    SEGMENT_ID_SBC_DECODE_BIN,
    SEGMENT_ID_WAV_ENCODE_BIN,
    SEGMENT_ID_AMR_ENCODE_BIN,
    SEGMENT_ID_XXX_ENCODE_BIN,
    SEGMENT_ID_FADE_MODULE,
    SEGMENT_ID_SHELL_CMD_NAME,
    SEGMENT_ID_TASK_INF,
    SEGMENT_ID_FW_SHELL,
    SEGMENT_ID_GPIO_SHELL,
    MAX_SEGMENT_NUM

} SEGMENT_ID;

//Code Info Table
typedef struct _SEGMENT_INFO_T
{
    UINT32 CodeLoadBase;
    UINT32 CodeImageBase;
    UINT32 CodeImageLength;

    UINT32 DataLoadBase;
    UINT32 DataImageBase;
    UINT32 DataImageLength;

    UINT32 BssImageBase;
    UINT32 BssImageLength;

} SEGMENT_INFO_T;

//Module Info
typedef struct _SEGMENT_INFO_TABLE
{
    UINT32                  SegmentNum;
    SEGMENT_INFO_T          Segment[MAX_SEGMENT_NUM];

} SEGMENT_INFO_TABLE;


//System Default Para
typedef struct _SYSTEM_DEFAULT_PARA_T
{
    //system default setting
    UINT32 SDEnable;
    UINT32 FMEnable;
    UINT32 KeyNumIndex;

    UINT32 gLanguage;
    UINT32 Volume;

    UINT32 BLMode;
    UINT32 BLevel;
    UINT32 BLtime;

    UINT32 SettingPowerOffTime;
    UINT32 IdlePowerOffTime;

    UINT32 AvlsEnabled;
    UINT32 BeepEnabled;
    UINT32 FactoryVolLimit;

    //Music default setting
    UINT32 MusicRepMode;
    UINT32 MusicPlayOrder;
    UINT32 MusicBassBoost;
    UINT32 MusicEqSel;
    UINT32 MusicPlayFxSel;

    //Video default setting

    //Radio default setting
    UINT32 FMArea;
    UINT32 FMStereo;
    UINT32 FMScanSensitivity;

    //Record default setting

    //Picture default setting
    UINT32 PicAutoPlayTime;

    //Text default setting
    UINT32 TextAutoPlayTime;

    //Image ID
    uint32 ImageIndex;

    //VolumeTableIndex ID
    //uint32 VolumeTableIndex; // 1 : General  ;  0 : Europe  //VolumeTableIndex will not be reset when reset default setting - weslly

    //mutiple language
    uint32 MenuMaxItem;
    uint32 LanguageTotle;   //TOTAL_LANAUAGE_NUM,LANGUAGE_MAX_COUNT
    uint32 LanguagesEnableTbl[64];//support 256 languange

} SYSTEM_DEFAULT_PARA_T;

/*
*-------------------------------------------------------------------------------
*
*                           Module Info
*
*-------------------------------------------------------------------------------
*/
//Firmware Info
typedef struct _FIRMWARE_INFO_T
{
    UINT32                  LoadStartBase;
    SEGMENT_INFO_TABLE      SegmentInfo;
    SYSTEM_DEFAULT_PARA_T   SysDefaultPara;

} FIRMWARE_INFO_T;

void SysBSSInit(void);
/*
********************************************************************************
*
*                         End of ModuleInfoTab.h
*
********************************************************************************
*/
#endif

